version: '2'

services:
  web:
    build:
      context: .
    volumes:
      - .:/var/app
    ports:
      - '3000:3000'
  db:
      image: postgres:9.6.2-alpine
      ports:
          - '5432:5432'
      volumes:
          - postgres96:/var/lib/postgresql/data
volumes:
  postgres96: